#!/usr/bin/env python
##
##  runner script (migmig !!). users start the program by calling this script
##
##  Note:  Make sure that "python" refers to "python2.*" in your env variables.
##
#
# examples :
#   runner get http://example.com/file.zip
#   runner -x8 -t10 -s5 http://example.com/file.zip
#   runner status <hash string>
#   runner merge ~/Downloads/dir1 ~/Downloads/dir2


"""
Usage:
  migmig (-h | --help)
  migmig --version
  migmig get HASH [-v...] [-s NAME] [-d NAME] [-x NAME] [-t NAME] [(--http-user NAME --http-password NAME)]
  migmig status HASH
  migmig merge [main_dir] [to_merge_dir]
  migmig update
  

Options:
  -h --help                 Show this screen.
  --version                 Show version.
  -v --verbose              Show debugs.
  -s, --chunk-size <var>    Minimum size of chunks. Not recommended to use this!
  -d, --directory <var>     Destination directory to download the chunks into it. [default: ~/Downloads]
  -x, --max-conn <var>      Maximum number of connections per server. [default: 6]
  -t, --max-tries <var>     Maximum number of tries when download fails. [default: 3]
  --http-user <var>
  --http-password <var>

"""



from migmig import core
from migmig import docopt

core.start(docopt.docopt(__doc__, version='migmig 0.1'))
